### ISSUE TITLE
Files do not get copied from guest to host

### ISSUE THREAD

**Issue by stephan1827** [eduardocasino/vmsmount#1]
I am starting the tool with vmsmount /LFN and it connects the shared folder. It seems that I can copy files from the host to guest fine but when I use xcopy to copy the same files back everything finishes without error but I do not see the files on the host.

**Comment by eduardocasino** [comment]
Hi, thank you for reporting this. Some info that would be helpful:

- VMSMOUNT version
- Host OS and filesystem type
- Guest OS and version (E.g. Freedos 1.0, MSDOS 5.0...)
- Mount permissions of the host filesystem
- Full VMSMOUNT and xcopy command line
- Steps to reproduce the issue.

If I understood the issue:

1. You mount a host file system into some unit, say X:
2. You xcopy from X:\somefldr to a local unit, say C:\somefldr
3. Files are copied OK into C:\somefldr
4. You xcopy back from C:\somefldr to X:\othrfldr
5. X:\othrfldr is empty

Is that correct?

Thanks!

**Comment by stephan1827** [comment]
Thx for the quick response, here are some details and a video of the issue

- VMSMOUNT version = 0.6
- Host OS and filesystem type = Windows 10
- Guest OS and version (E.g. Freedos 1.0, MSDOS 5.0...) = 0..84-pre2
- Mount permissions of the host filesystem = Write access, I can create folders just fine
- Full VMSMOUNT and xcopy command line = see video
- Steps to reproduce the
-  issue. = see video
![03-05-2023_08-17-16](https://user-images.githubusercontent.com/2972703/235844166-7b169dbc-f877-4bd7-ab09-43fa6f6ac154.gif)

**Comment by eduardocasino** [comment]
The problem affected to int 2Fh functions that receive parameters on the stack: 1117h (CreateFile) and 110Eh (SetAttr). In VMSMOUNT 0.6, I've changed the way that the redirector is called (there is an additional call) and I was not accessing the stack correctly.

The files were copied, but were created with (S)ystem, (H)idden and (R)ead-only attributes, that is why you could not see them. You can check it out executing ATTRIB in a command shell:

![attrib](https://user-images.githubusercontent.com/37220276/236060864-d3a48eed-3908-4eaf-b160-29dfe8914dbb.png)

Generated [new preview release](https://github.com/eduardocasino/vmsmount/releases/tag/v0.6-pre2).
