### ISSUE TITLE
Additional translations

### ISSUE THREAD

**Issue by cardpuncher** [eduardocasino/vmsmount#2]
Hi,

This is a question rather than a bug report, but the project's readme states that the program is "Currently only available in English, Spanish and Dutch" whereas there are additional German, French, Swedish and Turkish translations on <https://github.com/shidel/fd-nls/tree/master/vmsmount/nls>. These translations aren't in the nls directory of this project either, so I was wondering if this was normal or an oversight.

All the best.

**Comment by eduardocasino** [comment]
Hi,

Thank you for your interest in vmsmount. Those translations are part of the FreeDOS NLS project and are not directly maintained by me, but of course you can use them even if running any other DOS.

Cheers,
Eduardo

**Comment by cardpuncher** [comment]
On 17.06.2023 23:32, Eduardo Casino wrote:
> Hi,
> 
> Thank you for your interest in vmsmount. those translations are part of 
> the FreeDOS NLS project and are not directly maintained by me, but of 
> course you can use them even if running any other DOS.

Okay, if you're aware that these translations are on FD-NLS everything 
is fine :)

IMHO there's no reason to keep this report open anymore.
